version: "2"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kakebosan_production
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    command: bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      RAILS_MASTER_KEY:
      RAILS_SERVE_STATIC_FILES: "true"
      GITHUB_KEY:
      GITHUB_SECRET:
      PGPASSWORD: password
